[[main]]
  identifier = "about"
  name = "About us"
  url = "about"
  weight = 1

[[main]]
  identifier = "courses"
  name = "Courses"
  url = "courses"
  weight = 2

[[main]]
  identifier = "portfolio"
  name = "Portfolio"
  url = "portfolio"
  weight = 3

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 4

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 5
